dict:
  system:
    name: @project.name@
    title: @project.description@
    version: @project.version@
    remote_base_url: http://benzolamps.oss-cn-beijing.aliyuncs.com
    universe_path: templates/java/universe
    jdbc_file: dictionary.db
spring:
  datasource:
    driver_class_name: org.sqlite.JDBC
    url: jdbc:sqlite:${dict.system.jdbc_file}
  jpa:
    show_sql: false
    generate_ddl: true
    database_platform: com.benzolamps.dict.cfg.sqlite.SQLiteDialect
  mvc:
    view:
      prefix:
      suffix: .ftl
    favicon:
      enabled: false
    async:
      request_timeout: 30000
  resources:
    static_locations: file:templates/static
  jackson:
    time_zone: GMT+8
    date_format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  http:
    encoding:
      force: true
  freemarker:
    template_loader_path: file:templates
    settings:
      number_format: '#'
server:
  port: 2018
  context_path: /${dict.system.name}
  tomcat:
    uri-encoding: UTF-8

---
spring:
  profiles: default
logging:
  config: classpath:logback-spring.xml

---
spring:
  profiles: release
file:
  encoding: GBK
logging:
  config: classpath:logback-spring-release.xml

---
spring:
  profiles: test
logging:
  config: classpath:logback-spring-release.xml

---
spring:
  profiles: eclipse
logging:
  config: classpath:logback-spring-release.xml