dict:
  system:
    name: @project.name@
    title: @project.description@
    version: @project.version@
    remote_base_url: http://benzolamps.oss-cn-beijing.aliyuncs.com
    universe_path: templates/java/universe
  aip:
    app_id: ####
    api_key: ####
    secret_key: ####
spring:
  datasource:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dict?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: 123456
  jpa:
    show_sql: false
    generate_ddl: true
    database_platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    favicon:
      enabled: true
    view:
      prefix:
      suffix: .ftl
    async:
      request_timeout: 30000
  resources:
    static_locations: file:templates/static
  jackson:
    time_zone: GMT+8
    date_format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  freemarker:
    template_loader_path: file:templates
    settings:
      auto_include: view/includes/main.ftl
      number_format: '#'
server:
  port: 2018
  context_path: /${dict.system.name}
  tomcat:
    uri-encoding: UTF-8

---
spring:
  profiles: default
logging:
  pattern:
    console: '%cyan(**${dict.system.title} - ${dict.system.version}) %blue([%d{yyyy-MM-dd HH:mm:ss.SSS}]) %yellow(<%p>) %red(%logger) %cyan([%F:%L]) %n%m%n%n'
    file: '**${dict.system.title} - ${dict.system.version} [%d{yyyy-MM-dd HH:mm:ss.SSS}] <%p> %logger [%F:%L] %n%m%n%n'

---
spring:
  profiles:
    - release
    - test
    - eclipse
logging:
  pattern:
    console: '**${dict.system.title} - ${dict.system.version} [%d{yyyy-MM-dd HH:mm:ss.SSS}] <%p> %logger [%F:%L] %n%m%n%n'
    file: ${logging.pattern.console}

