baseProperties:
  chinese_font_family: 宋体
  english_font_family: Times New Roman
  font_size: 18
  line_height: 300
  separate_columns: 2
  show_separators: false
  insert_blank_line_between_words: false
  definition_arranges_vertically: false
  table_border_color: AAAAAA
  need_top_info: false
  top_info: ★特别提醒：请在一秒钟内不能准确翻译汉语意思的单词中部划横线。示例：
  top_info_base64: iVBORw0KGgoAAAANSUhEUgAAASQAAAAtCAYAAAAHgRaQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAW8SURBVHhe7Z3pUetKEIXZl3+kQAqkQAqkQAqkQAqkQAqkQAqkQAx+9fFo36bds8hLDRLnVH3FxZ61p3UkfC3N0UqSJOmXSIYkSdKvkQxpYXp9fV09Pj6ujo6OVvf399+vSr9d7+/vq7u7u691g+fn5+93/pZkSAvQx8fHVwJbMhsypHno8/NzdXNzs7F+f9GUZEgzFgnrz6oRGdI89Pb2lq4fV7p/TTKkmQozwnD4aX+iRWRI81DpCunl5eW7xN+RDGkhykxJhjQf6TOk/yVDWoj4MNubEciQpLlJhrQQZZ9DyJCkuUmGtBBxyS9DkuYuGdJCxH/9y5CkuUuGtBDJkKQlSIa0EMmQpCVIhrQQyZCkJUiGtBDJkKQlSIa0EMmQpCWoakh82e7p6Wkj0R8eHr6+Scp3XxAHA199t99/q3ruhOe/z5mbny/foN3nN2etj+w+NIvtVE0xJNYpruuuc/Rtxn65NYK2/e0RrANj7hVlaYO2rQ3Dxr6P/BuZIzZHi9OU+IwUt7jEeBi8PuUWmNSQCES28C1iQpTusSpxe3v7XTMX48rqeejTyxY5lsuSrTVekm6XJCE+mQmVmJLgWWyyOWJ4sZyH8WEgPbLYxvuwfL/MObtPC1jvVl/00Rqzh/FPNabROULf2fHW0w4xjPX2QTyOMmE0pbWNMM6eddkwJILgJ8lZLwaGAGYHVtYhg24dhFMOPMR4YpsxEUtjNHyyZe2VoNw28lckLGKcM2fdLCmzgyITc6jV3ecce2PLemTve7giKYl+fFkOEr/G2ZWXQbxbGpkj/kqsBH22dChDqq0Lcfe5Gj2CXC7NLeZ91IYh+aDXBoX8QQYlB2QCpcXk7LeNMDprI55pmTQB42fp7GrJRiCnLmorqFF+cei3dlXgF9roiRHziPV2mWPpMrs3tiRlz9mTcplo35cr5RYq5ZfNP1PvPNC+c4Tx2kkpztPjD/KSLMb8nPKnEeL4jn1Czcx9rIlJaf1Q6YRUi80PQzo/P19XOjk5WV1fXzehnNW5uLhIy8Dl5eW6nOf09DQt3+Ls7GzdBuPOyhj04fsExn11dfXjd9r09XwfEV+uRuybPrNyBjH05Y3WHP1cDJvj8fHx+vfYTmmO1PHlSpRia/+2mDKO2FcpX3rLebL5g/XfYmSOlNacvrPyHivL8ZW9X6IUr9a6Wy5Bz/i8p3hsvFE/DCmrKIQQhyJKhiSEGEbU+pXsMwghhDgkUetX+LAqqyCEEIci6scrWQUhhDgUUTIkIcQwomRIQohhRMmQhBDDiJIhCSGGESVDEkIMI0qGJIQYRpQMSQgxjCgZkhBiGFEyJCHEMKJkSEKIYUTJkIQQw4iSIQkhhhElQxJCDCNKhiSEGEZU0ZB6nmMM8ZnCrWc/t8iebdz7XOQS2XN9e58ZDdkzj3vql55bPJWeZxeXnsuclc3Ydo6lZ6X3jLmEfyb31DbjPHrzeFSOGLEutMZeyq8p/Xp8e633d4Fj3NqMql4h1XYHQHFniW13EPHKdiro2X2hptKWLL3t7lKfGGV1eyC2tV0dvA41x9oOKai0awbt7SJ2/IhtsstFbT4xd6bswjEyR0q7c7RimO20Qs70jtlEedbR72BSUjzmp8KYa2r+yUYSMNg4yZiI+zAjk0/G2lY2PSodMEBwatvroLjVk4f6PYZBH1MXsbXFjAnDqI2RdloH5jZzJB9q9YC1a8W3ptL2RDEfGZ83BGLd2sLLa2SO0DZrlNUFxpapFftdYDw1EfvamEuQD60T3F4+Q5q6H1RLfr+oKYllImB+fL1YktcStETrbEbbpQMsQluthdt1jqUzeg3qsNbZey22zRHqTTHzntih0TmSXQG2sL7RNobQS8uQTFNyqGSsURuGZGcDXJ1GIEsIAtrbyVSZ+9Pv0mRxjTHlTMrrPumkf+LEVMpFDgze6zEiab8i5sQ+M1hOwLzXr9XqP8Z6e0rm7jI7AAAAAElFTkSuQmCC
  white_base64: iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAVSURBVBhXY/z//z8DAwMTEDMwMAAAJAYDAbrboo8AAAAASUVORK5CYII=
solutions:
  - id: 0
    name: 单词生词表
    path: doc/universe/new_words.doc
    remark: 单词生词表
    needHeader: true
    exportFor: WORD
    needShuffle: false
    properties: {}
  - id: 1
    name: 单词抄写表
    path: doc/universe/copy_words.doc
    remark: 单词抄写表
    needHeader: true
    exportFor: WORD
    needShuffle: true
    properties: {}
  - id: 2
    name: 单词排查表
    path: doc/universe/check_words.doc
    remark: 单词排查表
    needHeader: true
    exportFor: WORD
    needShuffle: false
    properties:
      separate_columns: 4
      is_definition: false
      need_top_info: true
  - id: 3
    name: 单词词义排查表
    path: doc/universe/check_words.doc
    remark: 单词词义排查表
    needHeader: true
    exportFor: WORD
    needShuffle: false
    properties:
      separate_columns: 4
      is_definition: true
      need_top_info: true
  - id: 4
    name: 单词对照表
    path: doc/universe/collation_words.doc
    remark: 单词对照表
    needHeader: true
    exportFor: WORD
    needShuffle: false
    properties: {}
  - id: 5
    name: 短语生词表
    path: doc/universe/new_phrases.doc
    remark: 短语生词表
    needHeader: true
    exportFor: PHRASE
    needShuffle: false
    properties: {}
  - id: 6
    name: 短语抄写表
    path: doc/universe/copy_phrases.doc
    remark: 短语抄写表
    needHeader: true
    exportFor: PHRASE
    needShuffle: true
    properties: {}
  - id: 7
    name: 短语排查表
    path: doc/universe/check_phrases.doc
    remark: 短语排查表
    needHeader: true
    exportFor: PHRASE
    needShuffle: false
    properties:
      separate_columns: 4
      is_definition: false
      need_top_info: true
  - id: 8
    name: 短语词义排查表
    path: doc/universe/check_phrases.doc
    remark: 短语词义排查表
    needHeader: true
    exportFor: PHRASE
    needShuffle: false
    properties:
      separate_columns: 4
      is_definition: true
      need_top_info: true
  - id: 9
    name: 短语对照表
    path: doc/universe/collation_phrases.doc
    remark: 短语对照表
    needHeader: true
    exportFor: PHRASE
    needShuffle: false
    properties: {}